//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emelina_KS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Emelina_KSEntities : DbContext
    {
        private static Emelina_KSEntities _context;
        public static Emelina_KSEntities GetContext()
        {
            if (_context == null)
                _context = new Emelina_KSEntities();

            return _context;
        }
        public Emelina_KSEntities()
            : base("name=Emelina_KSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Группы> Группы { get; set; }
        public virtual DbSet<Дежурство> Дежурство { get; set; }
        public virtual DbSet<Отсутствующие> Отсутствующие { get; set; }
        public virtual DbSet<Пары> Пары { get; set; }
        public virtual DbSet<Подгруппы> Подгруппы { get; set; }
        public virtual DbSet<Преподаватели> Преподаватели { get; set; }
        public virtual DbSet<Студенты> Студенты { get; set; }
    }
}
