//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emelina_KS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Дежурство
    {
        public int Код_преподавателя { get; set; }
        public System.DateTime Дата { get; set; }
        public string Группа { get; set; }
        public int Код_дежурного1 { get; set; }
        public int Код_дежурного2 { get; set; }
    
        public virtual Преподаватели Преподаватели { get; set; }
        public virtual Студенты Студенты { get; set; }
        public virtual Студенты Студенты1 { get; set; }
    }
}
