//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emelina_KS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пары
    {
        public int Id { get; set; }
        public int Код_преподавателя { get; set; }
        public string День_недели { get; set; }
        public int Номер_пары { get; set; }
        public string Группа { get; set; }
        public virtual Группы Группы { get; set; }
        public virtual Преподаватели Преподаватели { get; set; }
    }
}
