//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emelina_KS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Преподаватели
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Преподаватели()
        {
            this.Дежурство = new HashSet<Дежурство>();
            this.Пары = new HashSet<Пары>();
        }
    
        public int Код_преподавателя { get; set; }
        public string Фамилия_преподавателя { get; set; }
        public string Имя_преподавателя { get; set; }
        public string Отчество_преподавателя { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Дежурство> Дежурство { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пары> Пары { get; set; }
        public virtual Подгруппы Подгруппы { get; set; }
    }
}
